"""
AI Test Generator - Genera test automatici per modelli FlaskERP
"""

import json
import logging
from typing import Dict, List, Any

logger = logging.getLogger(__name__)


class AITestGenerator:
    """
    Genera test cases automaticamente per modelli FlaskERP.
    """

    def __init__(self):
        self.test_types = ["create", "read", "update", "delete", "validation"]

    def generate_test_suite(
        self, sys_model, project_id: int, test_types: List[str] = None
    ) -> Dict:
        """
        Genera una test suite completa per un modello.

        Args:
            sys_model: Modello SysModel
            project_id: ID del progetto
            test_types: Lista tipi test da generare

        Returns:
            Dict con test_suite e test_cases
        """
        if test_types is None:
            test_types = self.test_types

        model_name = sys_model.name
        title = sys_model.title or model_name

        test_suite = {
            "nome": f"Test Suite {title}",
            "descrizione": f"Generated by AI for {title} model",
            "modulo_target": model_name,
            "test_type": "crud",
            "stato": "bozza",
        }

        test_cases = []
        order = 1

        # Generate test cases based on model fields
        fields = list(sys_model.fields) if hasattr(sys_model, "fields") else []

        for test_type in test_types:
            cases = self._generate_test_cases(
                model_name, title, fields, test_type, order
            )
            test_cases.extend(cases)
            order += len(cases)

        return {
            "test_suite": test_suite,
            "test_cases": test_cases,
            "summary": {
                "total_cases": len(test_cases),
                "by_type": self._count_by_type(test_cases),
            },
        }

    def _generate_test_cases(
        self,
        model_name: str,
        title: str,
        fields: List,
        test_type: str,
        start_order: int,
    ) -> List[Dict]:
        """Genera test cases per un tipo specifico."""
        cases = []

        if test_type == "create":
            cases.extend(
                self._generate_create_tests(model_name, title, fields, start_order)
            )
        elif test_type == "read":
            cases.extend(
                self._generate_read_tests(model_name, title, fields, start_order)
            )
        elif test_type == "update":
            cases.extend(
                self._generate_update_tests(model_name, title, fields, start_order)
            )
        elif test_type == "delete":
            cases.extend(self._generate_delete_tests(model_name, title, start_order))
        elif test_type == "validation":
            cases.extend(
                self._generate_validation_tests(model_name, title, fields, start_order)
            )

        return cases

    def _generate_create_tests(
        self, model_name, title, fields, start_order
    ) -> List[Dict]:
        """Genera test per creazione record."""
        test_data = self._generate_sample_data(fields, "create")

        return [
            {
                "nome": f"Create {title} - Success",
                "descrizione": f"Test successful creation of {title}",
                "ordine": start_order,
                "test_type": "create",
                "metodo": "POST",
                "endpoint": f"/api/v1/data/{model_name}",
                "payload": test_data,
                "expected_status": 201,
                "expected_fields": ["id"],
            },
            {
                "nome": f"Create {title} - Missing Required",
                "descrizione": f"Test creation without required fields",
                "ordine": start_order + 1,
                "test_type": "validation",
                "metodo": "POST",
                "endpoint": f"/api/v1/data/{model_name}",
                "payload": {},
                "expected_status": 400,
            },
        ]

    def _generate_read_tests(
        self, model_name, title, fields, start_order
    ) -> List[Dict]:
        """Genera test per lettura record."""
        return [
            {
                "nome": f"List {title}",
                "descrizione": f"Test listing {title} records",
                "ordine": start_order,
                "test_type": "read",
                "metodo": "GET",
                "endpoint": f"/api/v1/data/{model_name}",
                "payload": {"page": 1, "per_page": 10},
                "expected_status": 200,
            },
            {
                "nome": f"Get {title} by ID",
                "descrizione": f"Test getting single {title} record",
                "ordine": start_order + 1,
                "test_type": "read",
                "metodo": "GET",
                "endpoint": f"/api/v1/data/{model_name}/1",
                "payload": {},
                "expected_status": 200,
            },
            {
                "nome": f"Get {title} - Not Found",
                "descrizione": f"Test getting non-existent {title}",
                "ordine": start_order + 2,
                "test_type": "read",
                "metodo": "GET",
                "endpoint": f"/api/v1/data/{model_name}/99999",
                "payload": {},
                "expected_status": 404,
            },
        ]

    def _generate_update_tests(
        self, model_name, title, fields, start_order
    ) -> List[Dict]:
        """Genera test per aggiornamento record."""
        update_data = self._generate_sample_data(fields, "update")

        return [
            {
                "nome": f"Update {title} - Success",
                "descrizione": f"Test successful update of {title}",
                "ordine": start_order,
                "test_type": "update",
                "metodo": "PUT",
                "endpoint": f"/api/v1/data/{model_name}/1",
                "payload": update_data,
                "expected_status": 200,
            },
            {
                "nome": f"Update {title} - Not Found",
                "descrizione": f"Test updating non-existent {title}",
                "ordine": start_order + 1,
                "test_type": "update",
                "metodo": "PUT",
                "endpoint": f"/api/v1/data/{model_name}/99999",
                "payload": update_data,
                "expected_status": 404,
            },
        ]

    def _generate_delete_tests(self, model_name, title, start_order) -> List[Dict]:
        """Genera test per eliminazione record."""
        return [
            {
                "nome": f"Delete {title} - Success",
                "descrizione": f"Test successful deletion of {title}",
                "ordine": start_order,
                "test_type": "delete",
                "metodo": "DELETE",
                "endpoint": f"/api/v1/data/{model_name}/1",
                "payload": {},
                "expected_status": 200,
            },
            {
                "nome": f"Delete {title} - Not Found",
                "descrizione": f"Test deleting non-existent {title}",
                "ordine": start_order + 1,
                "test_type": "delete",
                "metodo": "DELETE",
                "endpoint": f"/api/v1/data/{model_name}/99999",
                "payload": {},
                "expected_status": 404,
            },
        ]

    def _generate_validation_tests(
        self, model_name, title, fields, start_order
    ) -> List[Dict]:
        """Genera test di validazione."""
        cases = []
        order = start_order

        for field in fields:
            if not hasattr(field, "type"):
                continue

            field_name = field.name
            field_type = field.type

            if field.required:
                cases.append(
                    {
                        "nome": f"Create {title} - Missing {field_name}",
                        "descrizione": f"Test creation without required field {field_name}",
                        "ordine": order,
                        "test_type": "validation",
                        "metodo": "POST",
                        "endpoint": f"/api/v1/data/{model_name}",
                        "payload": self._generate_sample_data(
                            fields, "create", exclude=[field_name]
                        ),
                        "expected_status": 400,
                    }
                )
                order += 1

            if (
                field_type == "string"
                and hasattr(field, "validation_regex")
                and field.validation_regex
            ):
                cases.append(
                    {
                        "nome": f"Create {title} - Invalid {field_name} Format",
                        "descrizione": f"Test creation with invalid {field_name} format",
                        "ordine": order,
                        "test_type": "validation",
                        "metodo": "POST",
                        "endpoint": f"/api/v1/data/{model_name}",
                        "payload": self._generate_sample_data(
                            fields, "create", invalid_field=field_name
                        ),
                        "expected_status": 400,
                    }
                )
                order += 1

        if not cases:
            cases.append(
                {
                    "nome": f"Create {title} - Duplicate",
                    "descrizione": f"Test creation with duplicate data",
                    "ordine": order,
                    "test_type": "validation",
                    "metodo": "POST",
                    "endpoint": f"/api/v1/data/{model_name}",
                    "payload": self._generate_sample_data(fields, "create"),
                    "expected_status": 409,
                }
            )

        return cases

    def _generate_sample_data(
        self,
        fields: List,
        operation: str,
        exclude: List[str] = None,
        invalid_field: str = None,
    ) -> Dict:
        """Genera dati di esempio per test."""
        if exclude is None:
            exclude = []

        data = {}

        for field in fields:
            if not hasattr(field, "name"):
                continue

            field_name = field.name
            field_type = getattr(field, "type", "string")

            if field_name in exclude:
                continue

            if invalid_field and field_name == invalid_field:
                data[field_name] = "!!!INVALID!!!"
                continue

            data[field_name] = self._get_sample_value(field_type, field)

        return data

    def _get_sample_value(self, field_type: str, field) -> Any:
        """Ottiene un valore di esempio per tipo campo."""
        if field_type == "string":
            return "Test string"
        elif field_type == "text":
            return "Test text content"
        elif field_type == "integer":
            return 42
        elif field_type == "decimal" or field_type == "float":
            return 10.5
        elif field_type == "boolean":
            return True
        elif field_type == "date":
            return "2024-01-01"
        elif field_type == "datetime":
            return "2024-01-01T12:00:00"
        elif field_type == "select":
            options = getattr(field, "options", None)
            if options:
                try:
                    opts = json.loads(options)
                    if isinstance(opts, list) and opts:
                        return (
                            opts[0].get("value")
                            if isinstance(opts[0], dict)
                            else opts[0]
                        )
                except:
                    pass
            return "option1"
        elif field_type == "tags":
            return ["tag1", "tag2"]

        return "test"

    def _count_by_type(self, test_cases: List[Dict]) -> Dict:
        """Conta test cases per tipo."""
        counts = {}
        for case in test_cases:
            t = case.get("test_type", "unknown")
            counts[t] = counts.get(t, 0) + 1
        return counts

    def save_test_suite(
        self, test_suite_data: Dict, test_cases_data: List[Dict], project_id: int
    ) -> Dict:
        """
        Salva la test suite e i test cases nel DB.

        Args:
            test_suite_data: Dati della test suite
            test_cases_data: Lista test cases
            project_id: ID progetto

        Returns:
            Dict con IDs creati
        """
        try:
            from backend.core.models.test_models import TestSuite, TestCase
            from backend.extensions import db

            test_suite = TestSuite(
                nome=test_suite_data["nome"],
                descrizione=test_suite_data.get("descrizione", ""),
                modulo_target=test_suite_data["modulo_target"],
                test_type=test_suite_data.get("test_type", "crud"),
                stato=test_suite_data.get("stato", "bozza"),
                is_active=True,
            )

            db.session.add(test_suite)
            db.session.flush()

            case_ids = []
            for case_data in test_cases_data:
                test_case = TestCase(
                    test_suite_id=test_suite.id,
                    nome=case_data["nome"],
                    descrizione=case_data.get("descrizione", ""),
                    ordine=case_data.get("ordine", 0),
                    test_type=case_data["test_type"],
                    metodo=case_data["metodo"],
                    endpoint=case_data["endpoint"],
                    payload=case_data.get("payload", {}),
                    expected_status=case_data.get("expected_status", 200),
                    expected_fields=case_data.get("expected_fields", []),
                    is_active=True,
                )
                db.session.add(test_case)
                db.session.flush()
                case_ids.append(test_case.id)

            db.session.commit()

            return {
                "success": True,
                "test_suite_id": test_suite.id,
                "test_cases_count": len(case_ids),
                "test_case_ids": case_ids,
            }

        except Exception as e:
            logger.error(f"Error saving test suite: {e}")
            return {"success": False, "error": str(e)}


ai_test_generator = AITestGenerator()
