"""Seed per la tabella nazioni (249 paesi)."""
from backend import create_app
from backend.extensions import db
from backend.modules.geografia.nazione import Nazione

NAZIONI = [
    {"codice_iso": "AFG", "codice_iso2": "AF", "nome": "Afghanistan", "nome_inglese": "Afghanistan", "continente": "AS", "nazionalita": "Afghana", "valuta": "AFN", "prefisso_telefonico": "+93"},
    {"codice_iso": "ALB", "codice_iso2": "AL", "nome": "Albania", "nome_inglese": "Albania", "continente": "EU", "nazionalita": "Albanese", "valuta": "ALL", "prefisso_telefonico": "+355"},
    {"codice_iso": "DZA", "codice_iso2": "DZ", "nome": "Algeria", "nome_inglese": "Algeria", "continente": "AF", "nazionalita": "Algerina", "valuta": "DZD", "prefisso_telefonico": "+213"},
    {"codice_iso": "AND", "codice_iso2": "AD", "nome": "Andorra", "nome_inglese": "Andorra", "continente": "EU", "nazionalita": "Andorrana", "valuta": "EUR", "prefisso_telefonico": "+376"},
    {"codice_iso": "AGO", "codice_iso2": "AO", "nome": "Angola", "nome_inglese": "Angola", "continente": "AF", "nazionalita": "Angolana", "valuta": "AOA", "prefisso_telefonico": "+244"},
    {"codice_iso": "ATG", "codice_iso2": "AG", "nome": "Antigua e Barbuda", "nome_inglese": "Antigua and Barbuda", "continente": "NA", "nazionalita": "Antiguana", "valuta": "XCD", "prefisso_telefonico": "+1-268"},
    {"codice_iso": "ARG", "codice_iso2": "AR", "nome": "Argentina", "nome_inglese": "Argentina", "continente": "SA", "nazionalita": "Argentino", "valuta": "ARS", "prefisso_telefonico": "+54"},
    {"codice_iso": "ARM", "codice_iso2": "AM", "nome": "Armenia", "nome_inglese": "Armenia", "continente": "AS", "nazionalita": "Armena", "valuta": "AMD", "prefisso_telefonico": "+374"},
    {"codice_iso": "AUS", "codice_iso2": "AU", "nome": "Australia", "nome_inglese": "Australia", "continente": "OC", "nazionalita": "Australiana", "valuta": "AUD", "prefisso_telefonico": "+61"},
    {"codice_iso": "AUT", "codice_iso2": "AT", "nome": "Austria", "nome_inglese": "Austria", "continente": "EU", "nazionalita": "Austriaca", "valuta": "EUR", "prefisso_telefonico": "+43"},
    {"codice_iso": "AZE", "codice_iso2": "AZ", "nome": "Azerbaigian", "nome_inglese": "Azerbaijan", "continente": "AS", "nazionalita": "Azerbaigiana", "valuta": "AZN", "prefisso_telefonico": "+994"},
    {"codice_iso": "BHS", "codice_iso2": "BS", "nome": "Bahamas", "nome_inglese": "Bahamas", "continente": "NA", "nazionalita": "Bahamense", "valuta": "BSD", "prefisso_telefonico": "+1-242"},
    {"codice_iso": "BHR", "codice_iso2": "BH", "nome": "Bahrein", "nome_inglese": "Bahrain", "continente": "AS", "nazionalita": "Bahreinita", "valuta": "BHD", "prefisso_telefonico": "+973"},
    {"codice_iso": "BGD", "codice_iso2": "BD", "nome": "Bangladesh", "nome_inglese": "Bangladesh", "continente": "AS", "nazionalita": "Bangladese", "valuta": "BDT", "prefisso_telefonico": "+880"},
    {"codice_iso": "BRB", "codice_iso2": "BB", "nome": "Barbados", "nome_inglese": "Barbados", "continente": "NA", "nazionalita": "Barbadiana", "valuta": "BBD", "prefisso_telefonico": "+1-246"},
    {"codice_iso": "BLR", "codice_iso2": "BY", "nome": "Bielorussia", "nome_inglese": "Belarus", "continente": "EU", "nazionalita": "Bielorussa", "valuta": "BYN", "prefisso_telefonico": "+375"},
    {"codice_iso": "BEL", "codice_iso2": "BE", "nome": "Belgio", "nome_inglese": "Belgium", "continente": "EU", "nazionalita": "Belga", "valuta": "EUR", "prefisso_telefonico": "+32"},
    {"codice_iso": "BLZ", "codice_iso2": "BZ", "nome": "Belize", "nome_inglese": "Belize", "continente": "NA", "nazionalita": "Beliziana", "valuta": "BZD", "prefisso_telefonico": "+501"},
    {"codice_iso": "BEN", "codice_iso2": "BJ", "nome": "Benin", "nome_inglese": "Benin", "continente": "AF", "nazionalita": "Beninese", "valuta": "XOF", "prefisso_telefonico": "+229"},
    {"codice_iso": "BTN", "codice_iso2": "BT", "nome": "Bhutan", "nome_inglese": "Bhutan", "continente": "AS", "nazionalita": "Bhutanese", "valuta": "BTN", "prefisso_telefonico": "+975"},
    {"codice_iso": "BOL", "codice_iso2": "BO", "nome": "Bolivia", "nome_inglese": "Bolivia", "continente": "SA", "nazionalita": "Boliviana", "valuta": "BOB", "prefisso_telefonico": "+591"},
    {"codice_iso": "BIH", "codice_iso2": "BA", "nome": "Bosnia ed Erzegovina", "nome_inglese": "Bosnia and Herzegovina", "continente": "EU", "nazionalita": "Bosniaca", "valuta": "BAM", "prefisso_telefonico": "+387"},
    {"codice_iso": "BWA", "codice_iso2": "BW", "nome": "Botswana", "nome_inglese": "Botswana", "continente": "AF", "nazionalita": "Botswana", "valuta": "BWP", "prefisso_telefonico": "+267"},
    {"codice_iso": "BRA", "codice_iso2": "BR", "nome": "Brasile", "nome_inglese": "Brazil", "continente": "SA", "nazionalita": "Brasiliana", "valuta": "BRL", "prefisso_telefonico": "+55"},
    {"codice_iso": "BRN", "codice_iso2": "BN", "nome": "Brunei", "nome_inglese": "Brunei", "continente": "AS", "nazionalita": "Bruneina", "valuta": "BND", "prefisso_telefonico": "+673"},
    {"codice_iso": "BGR", "codice_iso2": "BG", "nome": "Bulgaria", "nome_inglese": "Bulgaria", "continente": "EU", "nazionalita": "Bulgaro", "valuta": "BGN", "prefisso_telefonico": "+359"},
    {"codice_iso": "BFA", "codice_iso2": "BF", "nome": "Burkina Faso", "nome_inglese": "Burkina Faso", "continente": "AF", "nazionalita": "Burkinab\u00e8", "valuta": "XOF", "prefisso_telefonico": "+226"},
    {"codice_iso": "BDI", "codice_iso2": "BI", "nome": "Burundi", "nome_inglese": "Burundi", "continente": "AF", "nazionalita": "Burundese", "valuta": "BIF", "prefisso_telefonico": "+257"},
    {"codice_iso": "CPV", "codice_iso2": "CV", "nome": "Capo Verde", "nome_inglese": "Cabo Verde", "continente": "AF", "nazionalita": "Capoverdiana", "valuta": "CVE", "prefisso_telefonico": "+238"},
    {"codice_iso": "KHM", "codice_iso2": "KH", "nome": "Cambogia", "nome_inglese": "Cambodia", "continente": "AS", "nazionalita": "Cambogiana", "valuta": "KHR", "prefisso_telefonico": "+855"},
    {"codice_iso": "CMR", "codice_iso2": "CM", "nome": "Camerun", "nome_inglese": "Cameroon", "continente": "AF", "nazionalita": "Camerunese", "valuta": "XAF", "prefisso_telefonico": "+237"},
    {"codice_iso": "CAN", "codice_iso2": "CA", "nome": "Canada", "nome_inglese": "Canada", "continente": "NA", "nazionalita": "Canadese", "valuta": "CAD", "prefisso_telefonico": "+1"},
    {"codice_iso": "CAF", "codice_iso2": "CF", "nome": "Repubblica Centrafricana", "nome_inglese": "Central African Republic", "continente": "AF", "nazionalita": "Centrafricana", "valuta": "XAF", "prefisso_telefonico": "+236"},
    {"codice_iso": "TCD", "codice_iso2": "TD", "nome": "Ciad", "nome_inglese": "Chad", "continente": "AF", "nazionalita": "Ciadiana", "valuta": "XAF", "prefisso_telefonico": "+235"},
    {"codice_iso": "CHL", "codice_iso2": "CL", "nome": "Cile", "nome_inglese": "Chile", "continente": "SA", "nazionalita": "Cilena", "valuta": "CLP", "prefisso_telefonico": "+56"},
    {"codice_iso": "CHN", "codice_iso2": "CN", "nome": "Cina", "nome_inglese": "China", "continente": "AS", "nazionalita": "Cinese", "valuta": "CNY", "prefisso_telefonico": "+86"},
    {"codice_iso": "COL", "codice_iso2": "CO", "nome": "Colombia", "nome_inglese": "Colombia", "continente": "SA", "nazionalita": "Colombiana", "valuta": "COP", "prefisso_telefonico": "+57"},
    {"codice_iso": "COM", "codice_iso2": "KM", "nome": "Comore", "nome_inglese": "Comoros", "continente": "AF", "nazionalita": "Comoriana", "valuta": "KMF", "prefisso_telefonico": "+269"},
    {"codice_iso": "COG", "codice_iso2": "CG", "nome": "Repubblica del Congo", "nome_inglese": "Congo", "continente": "AF", "nazionalita": "Congolese", "valuta": "XAF", "prefisso_telefonico": "+242"},
    {"codice_iso": "COD", "codice_iso2": "CD", "nome": "Repubblica Democratica del Congo", "nome_inglese": "Democratic Republic of the Congo", "continente": "AF", "nazionalita": "Congolese", "valuta": "CDF", "prefisso_telefonico": "+243"},
    {"codice_iso": "CRI", "codice_iso2": "CR", "nome": "Costa Rica", "nome_inglese": "Costa Rica", "continente": "NA", "nazionalita": "Costaricana", "valuta": "CRC", "prefisso_telefonico": "+506"},
    {"codice_iso": "CIV", "codice_iso2": "CI", "nome": "Costa d'Avorio", "nome_inglese": "C\u00f4te d'Ivoire", "continente": "AF", "nazionalita": "Ivoriata", "valuta": "XOF", "prefisso_telefonico": "+225"},
    {"codice_iso": "HRV", "codice_iso2": "HR", "nome": "Croazia", "nome_inglese": "Croatia", "continente": "EU", "nazionalita": "Croata", "valuta": "HRK", "prefisso_telefonico": "+385"},
    {"codice_iso": "CUB", "codice_iso2": "CU", "nome": "Cuba", "nome_inglese": "Cuba", "continente": "NA", "nazionalita": "Cubana", "valuta": "CUP", "prefisso_telefonico": "+53"},
    {"codice_iso": "CYP", "codice_iso2": "CY", "nome": "Cipro", "nome_inglese": "Cyprus", "continente": "EU", "nazionalita": "Cipriota", "valuta": "EUR", "prefisso_telefonico": "+357"},
    {"codice_iso": "CZE", "codice_iso2": "CZ", "nome": "Repubblica Ceca", "nome_inglese": "Czech Republic", "continente": "EU", "nazionalita": "Ceca", "valuta": "CZK", "prefisso_telefonico": "+420"},
    {"codice_iso": "DNK", "codice_iso2": "DK", "nome": "Danimarca", "nome_inglese": "Denmark", "continente": "EU", "nazionalita": "Danese", "valuta": "DKK", "prefisso_telefonico": "+45"},
    {"codice_iso": "DJI", "codice_iso2": "DJ", "nome": "Gibuti", "nome_inglese": "Djibouti", "continente": "AF", "nazionalita": "Gibutiana", "valuta": "DJF", "prefisso_telefonico": "+253"},
    {"codice_iso": "DMA", "codice_iso2": "DM", "nome": "Dominica", "nome_inglese": "Dominica", "continente": "NA", "nazionalita": "Dominichese", "valuta": "XCD", "prefisso_telefonico": "+1-767"},
    {"codice_iso": "DOM", "codice_iso2": "DO", "nome": "Repubblica Dominicana", "nome_inglese": "Dominican Republic", "continente": "NA", "nazionalita": "Dominicana", "valuta": "DOP", "prefisso_telefonico": "+1-809"},
    {"codice_iso": "ECU", "codice_iso2": "EC", "nome": "Ecuador", "nome_inglese": "Ecuador", "continente": "SA", "nazionalita": "Ecuadoriana", "valuta": "USD", "prefisso_telefonico": "+593"},
    {"codice_iso": "EGY", "codice_iso2": "EG", "nome": "Egitto", "nome_inglese": "Egypt", "continente": "AF", "nazionalita": "Egiziana", "valuta": "EGP", "prefisso_telefonico": "+20"},
    {"codice_iso": "SLV", "codice_iso2": "SV", "nome": "El Salvador", "nome_inglese": "El Salvador", "continente": "NA", "nazionalita": "Salvadoregna", "valuta": "USD", "prefisso_telefonico": "+503"},
    {"codice_iso": "GNQ", "codice_iso2": "GQ", "nome": "Guinea Equatoriale", "nome_inglese": "Equatorial Guinea", "continente": "AF", "nazionalita": "Equatoguineana", "valuta": "XAF", "prefisso_telefonico": "+240"},
    {"codice_iso": "ERI", "codice_iso2": "ER", "nome": "Eritrea", "nome_inglese": "Eritrea", "continente": "AF", "nazionalita": "Eritrea", "valuta": "ERN", "prefisso_telefonico": "+291"},
    {"codice_iso": "EST", "codice_iso2": "EE", "nome": "Estonia", "nome_inglese": "Estonia", "continente": "EU", "nazionalita": "Estone", "valuta": "EUR", "prefisso_telefonico": "+372"},
    {"codice_iso": "SWZ", "codice_iso2": "SZ", "nome": "eSwatini", "nome_inglese": "Eswatini", "continente": "AF", "nazionalita": "Swazilandese", "valuta": "SZL", "prefisso_telefonico": "+268"},
    {"codice_iso": "ETH", "codice_iso2": "ET", "nome": "Etiopia", "nome_inglese": "Ethiopia", "continente": "AF", "nazionalita": "Etiope", "valuta": "ETB", "prefisso_telefonico": "+251"},
    {"codice_iso": "FJI", "codice_iso2": "FJ", "nome": "Figi", "nome_inglese": "Fiji", "continente": "OC", "nazionalita": "Figiana", "valuta": "FJD", "prefisso_telefonico": "+679"},
    {"codice_iso": "FIN", "codice_iso2": "FI", "nome": "Finlandia", "nome_inglese": "Finland", "continente": "EU", "nazionalita": "Finlandese", "valuta": "EUR", "prefisso_telefonico": "+358"},
    {"codice_iso": "FRA", "codice_iso2": "FR", "nome": "Francia", "nome_inglese": "France", "continente": "EU", "nazionalita": "Francese", "valuta": "EUR", "prefisso_telefonico": "+33"},
    {"codice_iso": "GAB", "codice_iso2": "GA", "nome": "Gabon", "nome_inglese": "Gabon", "continente": "AF", "nazionalita": "Gabonese", "valuta": "XAF", "prefisso_telefonico": "+241"},
    {"codice_iso": "GMB", "codice_iso2": "GM", "nome": "Gambia", "nome_inglese": "Gambia", "continente": "AF", "nazionalita": "Gambiana", "valuta": "GMD", "prefisso_telefonico": "+220"},
    {"codice_iso": "GEO", "codice_iso2": "GE", "nome": "Georgia", "nome_inglese": "Georgia", "continente": "AS", "nazionalita": "Georgiana", "valuta": "GEL", "prefisso_telefonico": "+995"},
    {"codice_iso": "DEU", "codice_iso2": "DE", "nome": "Germania", "nome_inglese": "Germany", "continente": "EU", "nazionalita": "Tedesca", "valuta": "EUR", "prefisso_telefonico": "+49"},
    {"codice_iso": "GHA", "codice_iso2": "GH", "nome": "Ghana", "nome_inglese": "Ghana", "continente": "AF", "nazionalita": "Ghanese", "valuta": "GHS", "prefisso_telefonico": "+233"},
    {"codice_iso": "GRC", "codice_iso2": "GR", "nome": "Grecia", "nome_inglese": "Greece", "continente": "EU", "nazionalita": "Greca", "valuta": "EUR", "prefisso_telefonico": "+30"},
    {"codice_iso": "GRD", "codice_iso2": "GD", "nome": "Grenada", "nome_inglese": "Grenada", "continente": "NA", "nazionalita": "Grenadina", "valuta": "XCD", "prefisso_telefonico": "+1-473"},
    {"codice_iso": "GTM", "codice_iso2": "GT", "nome": "Guatemala", "nome_inglese": "Guatemala", "continente": "NA", "nazionalita": "Guatemalteca", "valuta": "GTQ", "prefisso_telefonico": "+502"},
    {"codice_iso": "GIN", "codice_iso2": "GN", "nome": "Guinea", "nome_inglese": "Guinea", "continente": "AF", "nazionalita": "Guineana", "valuta": "GNF", "prefisso_telefonico": "+224"},
    {"codice_iso": "GNB", "codice_iso2": "GW", "nome": "Guinea-Bissau", "nome_inglese": "Guinea-Bissau", "continente": "AF", "nazionalita": "Guineana", "valuta": "XOF", "prefisso_telefonico": "+245"},
    {"codice_iso": "GUY", "codice_iso2": "GY", "nome": "Guyana", "nome_inglese": "Guyana", "continente": "SA", "nazionalita": "Guyanese", "valuta": "GYD", "prefisso_telefonico": "+592"},
    {"codice_iso": "HTI", "codice_iso2": "HT", "nome": "Haiti", "nome_inglese": "Haiti", "continente": "NA", "nazionalita": "Haitiano", "valuta": "HTG", "prefisso_telefonico": "+509"},
    {"codice_iso": "HND", "codice_iso2": "HN", "nome": "Honduras", "nome_inglese": "Honduras", "continente": "NA", "nazionalita": "Honduregna", "valuta": "HNL", "prefisso_telefonico": "+504"},
    {"codice_iso": "HUN", "codice_iso2": "HU", "nome": "Ungheria", "nome_inglese": "Hungary", "continente": "EU", "nazionalita": "Ungherese", "valuta": "HUF", "prefisso_telefonico": "+36"},
    {"codice_iso": "ISL", "codice_iso2": "IS", "nome": "Islanda", "nome_inglese": "Iceland", "continente": "EU", "nazionalita": "Islandese", "valuta": "ISK", "prefisso_telefonico": "+354"},
    {"codice_iso": "IND", "codice_iso2": "IN", "nome": "India", "nome_inglese": "India", "continente": "AS", "nazionalita": "Indiana", "valuta": "INR", "prefisso_telefonico": "+91"},
    {"codice_iso": "IDN", "codice_iso2": "ID", "nome": "Indonesia", "nome_inglese": "Indonesia", "continente": "AS", "nazionalita": "Indonesiana", "valuta": "IDR", "prefisso_telefonico": "+62"},
    {"codice_iso": "IRN", "codice_iso2": "IR", "nome": "Iran", "nome_inglese": "Iran", "continente": "AS", "nazionalita": "Iraniana", "valuta": "IRR", "prefisso_telefonico": "+98"},
    {"codice_iso": "IRQ", "codice_iso2": "IQ", "nome": "Iraq", "nome_inglese": "Iraq", "continente": "AS", "nazionalita": "Irachena", "valuta": "IQD", "prefisso_telefonico": "+964"},
    {"codice_iso": "IRL", "codice_iso2": "IE", "nome": "Irlanda", "nome_inglese": "Ireland", "continente": "EU", "nazionalita": "Irlandese", "valuta": "EUR", "prefisso_telefonico": "+353"},
    {"codice_iso": "ISR", "codice_iso2": "IL", "nome": "Israele", "nome_inglese": "Israel", "continente": "AS", "nazionalita": "Israeliana", "valuta": "ILS", "prefisso_telefonico": "+972"},
    {"codice_iso": "ITA", "codice_iso2": "IT", "nome": "Italia", "nome_inglese": "Italy", "continente": "EU", "nazionalita": "Italiana", "valuta": "EUR", "prefisso_telefonico": "+39"},
    {"codice_iso": "JAM", "codice_iso2": "JM", "nome": "Giamaica", "nome_inglese": "Jamaica", "continente": "NA", "nazionalita": "Giamaicana", "valuta": "JMD", "prefisso_telefonico": "+1-876"},
    {"codice_iso": "JPN", "codice_iso2": "JP", "nome": "Giappone", "nome_inglese": "Japan", "continente": "AS", "nazionalita": "Giapponese", "valuta": "JPY", "prefisso_telefonico": "+81"},
    {"codice_iso": "JOR", "codice_iso2": "JO", "nome": "Giordania", "nome_inglese": "Jordan", "continente": "AS", "nazionalita": "Giordana", "valuta": "JOD", "prefisso_telefonico": "+962"},
    {"codice_iso": "KAZ", "codice_iso2": "KZ", "nome": "Kazakistan", "nome_inglese": "Kazakhstan", "continente": "AS", "nazionalita": "Kazaka", "valuta": "KZT", "prefisso_telefonico": "+7"},
    {"codice_iso": "KEN", "codice_iso2": "KE", "nome": "Kenya", "nome_inglese": "Kenya", "continente": "AF", "nazionalita": "Keniota", "valuta": "KES", "prefisso_telefonico": "+254"},
    {"codice_iso": "KIR", "codice_iso2": "KI", "nome": "Kiribati", "nome_inglese": "Kiribati", "continente": "OC", "nazionalita": "Kiribatese", "valuta": "AUD", "prefisso_telefonico": "+686"},
    {"codice_iso": "PRK", "codice_iso2": "KP", "nome": "Corea del Nord", "nome_inglese": "North Korea", "continente": "AS", "nazionalita": "Nordcoreana", "valuta": "KPW", "prefisso_telefonico": "+850"},
    {"codice_iso": "KOR", "codice_iso2": "KR", "nome": "Corea del Sud", "nome_inglese": "South Korea", "continente": "AS", "nazionalita": "Sudcoreana", "valuta": "KRW", "prefisso_telefonico": "+82"},
    {"codice_iso": "XKX", "codice_iso2": "XK", "nome": "Kosovo", "nome_inglese": "Kosovo", "continente": "EU", "nazionalita": "Kosovara", "valuta": "EUR", "prefisso_telefonico": "+383"},
    {"codice_iso": "KWT", "codice_iso2": "KW", "nome": "Kuwait", "nome_inglese": "Kuwait", "continente": "AS", "nazionalita": "Kuwaitina", "valuta": "KWD", "prefisso_telefonico": "+965"},
    {"codice_iso": "KGZ", "codice_iso2": "KG", "nome": "Kirghizistan", "nome_inglese": "Kyrgyzstan", "continente": "AS", "nazionalita": "Kirghiza", "valuta": "KGS", "prefisso_telefonico": "+996"},
    {"codice_iso": "LAO", "codice_iso2": "LA", "nome": "Laos", "nome_inglese": "Laos", "continente": "AS", "nazionalita": "Laotiana", "valuta": "LAK", "prefisso_telefonico": "+856"},
    {"codice_iso": "LVA", "codice_iso2": "LV", "nome": "Lettonia", "nome_inglese": "Latvia", "continente": "EU", "nazionalita": "Lettone", "valuta": "EUR", "prefisso_telefonico": "+371"},
    {"codice_iso": "LBN", "codice_iso2": "LB", "nome": "Libano", "nome_inglese": "Lebanon", "continente": "AS", "nazionalita": "Libanese", "valuta": "LBP", "prefisso_telefonico": "+961"},
    {"codice_iso": "LSO", "codice_iso2": "LS", "nome": "Lesotho", "nome_inglese": "Lesotho", "continente": "AF", "nazionalita": "Lesothiana", "valuta": "LSL", "prefisso_telefonico": "+266"},
    {"codice_iso": "LBR", "codice_iso2": "LR", "nome": "Liberia", "nome_inglese": "Liberia", "continente": "AF", "nazionalita": "Liberiana", "valuta": "LRD", "prefisso_telefonico": "+231"},
    {"codice_iso": "LBY", "codice_iso2": "LY", "nome": "Libia", "nome_inglese": "Libya", "continente": "AF", "nazionalita": "Libica", "valuta": "LYD", "prefisso_telefonico": "+218"},
    {"codice_iso": "LIE", "codice_iso2": "LI", "nome": "Liechtenstein", "nome_inglese": "Liechtenstein", "continente": "EU", "nazionalita": "Liechtensteinese", "valuta": "CHF", "prefisso_telefonico": "+423"},
    {"codice_iso": "LTU", "codice_iso2": "LT", "nome": "Lituania", "nome_inglese": "Lithuania", "continente": "EU", "nazionalita": "Lituana", "valuta": "EUR", "prefisso_telefonico": "+370"},
    {"codice_iso": "LUX", "codice_iso2": "LU", "nome": "Lussemburgo", "nome_inglese": "Luxembourg", "continente": "EU", "nazionalita": "Lussemburghese", "valuta": "EUR", "prefisso_telefonico": "+352"},
    {"codice_iso": "MDG", "codice_iso2": "MG", "nome": "Madagascar", "nome_inglese": "Madagascar", "continente": "AF", "nazionalita": "Malagasia", "valuta": "MGA", "prefisso_telefonico": "+261"},
    {"codice_iso": "MWI", "codice_iso2": "MW", "nome": "Malawi", "nome_inglese": "Malawi", "continente": "AF", "nazionalita": "Malawiana", "valuta": "MWK", "prefisso_telefonico": "+265"},
    {"codice_iso": "MYS", "codice_iso2": "MY", "nome": "Malesia", "nome_inglese": "Malaysia", "continente": "AS", "nazionalita": "Malese", "valuta": "MYR", "prefisso_telefonico": "+60"},
    {"codice_iso": "MDV", "codice_iso2": "MV", "nome": "Maldive", "nome_inglese": "Maldives", "continente": "AS", "nazionalita": "Maldiviana", "valuta": "MVR", "prefisso_telefonico": "+960"},
    {"codice_iso": "MLI", "codice_iso2": "ML", "nome": "Mali", "nome_inglese": "Mali", "continente": "AF", "nazionalita": "Malese", "valuta": "XOF", "prefisso_telefonico": "+223"},
    {"codice_iso": "MLT", "codice_iso2": "MT", "nome": "Malta", "nome_inglese": "Malta", "continente": "EU", "nazionalita": "Maltese", "valuta": "EUR", "prefisso_telefonico": "+356"},
    {"codice_iso": "MHL", "codice_iso2": "MH", "nome": "Isole Marshall", "nome_inglese": "Marshall Islands", "continente": "OC", "nazionalita": "Marshallese", "valuta": "USD", "prefisso_telefonico": "+692"},
    {"codice_iso": "MRT", "codice_iso2": "MR", "nome": "Mauritania", "nome_inglese": "Mauritania", "continente": "AF", "nazionalita": "Mauritana", "valuta": "MRU", "prefisso_telefonico": "+222"},
    {"codice_iso": "MUS", "codice_iso2": "MU", "nome": "Mauritius", "nome_inglese": "Mauritius", "continente": "AF", "nazionalita": "Mauriziana", "valuta": "MUR", "prefisso_telefonico": "+230"},
    {"codice_iso": "MEX", "codice_iso2": "MX", "nome": "Messico", "nome_inglese": "Mexico", "continente": "NA", "nazionalita": "Messicana", "valuta": "MXN", "prefisso_telefonico": "+52"},
    {"codice_iso": "FSM", "codice_iso2": "FM", "nome": "Micronesia", "nome_inglese": "Micronesia", "continente": "OC", "nazionalita": "Micronesiana", "valuta": "USD", "prefisso_telefonico": "+691"},
    {"codice_iso": "MDA", "codice_iso2": "MD", "nome": "Moldavia", "nome_inglese": "Moldova", "continente": "EU", "nazionalita": "Moldava", "valuta": "MDL", "prefisso_telefonico": "+373"},
    {"codice_iso": "MCO", "codice_iso2": "MC", "nome": "Monaco", "nome_inglese": "Monaco", "continente": "EU", "nazionalita": "Monegasca", "valuta": "EUR", "prefisso_telefonico": "+377"},
    {"codice_iso": "MNG", "codice_iso2": "MN", "nome": "Mongolia", "nome_inglese": "Mongolia", "continente": "AS", "nazionalita": "Mongola", "valuta": "MNT", "prefisso_telefonico": "+976"},
    {"codice_iso": "MNE", "codice_iso2": "ME", "nome": "Montenegro", "nome_inglese": "Montenegro", "continente": "EU", "nazionalita": "Montenegrina", "valuta": "EUR", "prefisso_telefonico": "+382"},
    {"codice_iso": "MAR", "codice_iso2": "MA", "nome": "Marocco", "nome_inglese": "Morocco", "continente": "AF", "nazionalita": "Marocchina", "valuta": "MAD", "prefisso_telefonico": "+212"},
    {"codice_iso": "MOZ", "codice_iso2": "MZ", "nome": "Mozambico", "nome_inglese": "Mozambique", "continente": "AF", "nazionalita": "Mozambicana", "valuta": "MZN", "prefisso_telefonico": "+258"},
    {"codice_iso": "MMR", "codice_iso2": "MM", "nome": "Myanmar", "nome_inglese": "Myanmar", "continente": "AS", "nazionalita": "Birmana", "valuta": "MMK", "prefisso_telefonico": "+95"},
    {"codice_iso": "NAM", "codice_iso2": "NA", "nome": "Namibia", "nome_inglese": "Namibia", "continente": "AF", "nazionalita": "Namibiana", "valuta": "NAD", "prefisso_telefonico": "+264"},
    {"codice_iso": "NRU", "codice_iso2": "NR", "nome": "Nauru", "nome_inglese": "Nauru", "continente": "OC", "nazionalita": "Nauruana", "valuta": "AUD", "prefisso_telefonico": "+674"},
    {"codice_iso": "NPL", "codice_iso2": "NP", "nome": "Nepal", "nome_inglese": "Nepal", "continente": "AS", "nazionalita": "Nepalese", "valuta": "NPR", "prefisso_telefonico": "+977"},
    {"codice_iso": "NLD", "codice_iso2": "NL", "nome": "Paesi Bassi", "nome_inglese": "Netherlands", "continente": "EU", "nazionalita": "Olandese", "valuta": "EUR", "prefisso_telefonico": "+31"},
    {"codice_iso": "NZL", "codice_iso2": "NZ", "nome": "Nuova Zelanda", "nome_inglese": "New Zealand", "continente": "OC", "nazionalita": "Neozelandese", "valuta": "NZD", "prefisso_telefonico": "+64"},
    {"codice_iso": "NIC", "codice_iso2": "NI", "nome": "Nicaragua", "nome_inglese": "Nicaragua", "continente": "NA", "nazionalita": "Nicaraguense", "valuta": "NIO", "prefisso_telefonico": "+505"},
    {"codice_iso": "NER", "codice_iso2": "NE", "nome": "Niger", "nome_inglese": "Niger", "continente": "AF", "nazionalita": "Nigerina", "valuta": "XOF", "prefisso_telefonico": "+227"},
    {"codice_iso": "NGA", "codice_iso2": "NG", "nome": "Nigeria", "nome_inglese": "Nigeria", "continente": "AF", "nazionalita": "Nigeriana", "valuta": "NGN", "prefisso_telefonico": "+234"},
    {"codice_iso": "MKD", "codice_iso2": "MK", "nome": "Macedonia del Nord", "nome_inglese": "North Macedonia", "continente": "EU", "nazionalita": "Macedone", "valuta": "MKD", "prefisso_telefonico": "+389"},
    {"codice_iso": "NOR", "codice_iso2": "NO", "nome": "Norvegia", "nome_inglese": "Norway", "continente": "EU", "nazionalita": "Norvegese", "valuta": "NOK", "prefisso_telefonico": "+47"},
    {"codice_iso": "OMN", "codice_iso2": "OM", "nome": "Oman", "nome_inglese": "Oman", "continente": "AS", "nazionalita": "Omanita", "valuta": "OMR", "prefisso_telefonico": "+968"},
    {"codice_iso": "PAK", "codice_iso2": "PK", "nome": "Pakistan", "nome_inglese": "Pakistan", "continente": "AS", "nazionalita": "Pakistana", "valuta": "PKR", "prefisso_telefonico": "+92"},
    {"codice_iso": "PLW", "codice_iso2": "PW", "nome": "Palau", "nome_inglese": "Palau", "continente": "OC", "nazionalita": "Palauana", "valuta": "USD", "prefisso_telefonico": "+680"},
    {"codice_iso": "PSE", "codice_iso2": "PS", "nome": "Palestina", "nome_inglese": "Palestine", "continente": "AS", "nazionalita": "Palestinese", "valuta": "ILS", "prefisso_telefonico": "+970"},
    {"codice_iso": "PAN", "codice_iso2": "PA", "nome": "Panam\u00e1", "nome_inglese": "Panama", "continente": "NA", "nazionalita": "Panamense", "valuta": "PAB", "prefisso_telefonico": "+507"},
    {"codice_iso": "PNG", "codice_iso2": "PG", "nome": "Papua Nuova Guinea", "nome_inglese": "Papua New Guinea", "continente": "OC", "nazionalita": "Papua", "valuta": "PGK", "prefisso_telefonico": "+675"},
    {"codice_iso": "PRY", "codice_iso2": "PY", "nome": "Paraguay", "nome_inglese": "Paraguay", "continente": "SA", "nazionalita": "Paraguaiana", "valuta": "PYG", "prefisso_telefonico": "+595"},
    {"codice_iso": "PER", "codice_iso2": "PE", "nome": "Per\u00f9", "nome_inglese": "Peru", "continente": "SA", "nazionalita": "Peruviana", "valuta": "PEN", "prefisso_telefonico": "+51"},
    {"codice_iso": "PHL", "codice_iso2": "PH", "nome": "Filippine", "nome_inglese": "Philippines", "continente": "AS", "nazionalita": "Filippina", "valuta": "PHP", "prefisso_telefonico": "+63"},
    {"codice_iso": "POL", "codice_iso2": "PL", "nome": "Polonia", "nome_inglese": "Poland", "continente": "EU", "nazionalita": "Polacca", "valuta": "PLN", "prefisso_telefonico": "+48"},
    {"codice_iso": "PRT", "codice_iso2": "PT", "nome": "Portogallo", "nome_inglese": "Portugal", "continente": "EU", "nazionalita": "Portoghese", "valuta": "EUR", "prefisso_telefonico": "+351"},
    {"codice_iso": "QAT", "codice_iso2": "QA", "nome": "Qatar", "nome_inglese": "Qatar", "continente": "AS", "nazionalita": "Qatariana", "valuta": "QAR", "prefisso_telefonico": "+974"},
    {"codice_iso": "ROU", "codice_iso2": "RO", "nome": "Romania", "nome_inglese": "Romania", "continente": "EU", "nazionalita": "Romena", "valuta": "RON", "prefisso_telefonico": "+40"},
    {"codice_iso": "RUS", "codice_iso2": "RU", "nome": "Russia", "nome_inglese": "Russia", "continente": "EU", "nazionalita": "Russa", "valuta": "RUB", "prefisso_telefonico": "+7"},
    {"codice_iso": "RWA", "codice_iso2": "RW", "nome": "Ruanda", "nome_inglese": "Rwanda", "continente": "AF", "nazionalita": "Ruandese", "valuta": "RWF", "prefisso_telefonico": "+250"},
    {"codice_iso": "KNA", "codice_iso2": "KN", "nome": "Saint Kitts e Nevis", "nome_inglese": "Saint Kitts and Nevis", "continente": "NA", "nazionalita": "Kittitiana", "valuta": "XCD", "prefisso_telefonico": "+1-869"},
    {"codice_iso": "LCA", "codice_iso2": "LC", "nome": "Saint Lucia", "nome_inglese": "Saint Lucia", "continente": "NA", "nazionalita": "Santaluciana", "valuta": "XCD", "prefisso_telefonico": "+1-758"},
    {"codice_iso": "VCT", "codice_iso2": "VC", "nome": "Saint Vincent e Grenadine", "nome_inglese": "Saint Vincent and the Grenadines", "continente": "NA", "nazionalita": "Sanvincentina", "valuta": "XCD", "prefisso_telefonico": "+1-784"},
    {"codice_iso": "WSM", "codice_iso2": "WS", "nome": "Samoa", "nome_inglese": "Samoa", "continente": "OC", "nazionalita": "Samoana", "valuta": "WST", "prefisso_telefonico": "+685"},
    {"codice_iso": "SMR", "codice_iso2": "SM", "nome": "San Marino", "nome_inglese": "San Marino", "continente": "EU", "nazionalita": "Sammarinese", "valuta": "EUR", "prefisso_telefonico": "+378"},
    {"codice_iso": "STP", "codice_iso2": "ST", "nome": "S\u00e3o Tom\u00e9 e Pr\u00edncipe", "nome_inglese": "Sao Tome and Principe", "continente": "AF", "nazionalita": "Santomense", "valuta": "STN", "prefisso_telefonico": "+239"},
    {"codice_iso": "SAU", "codice_iso2": "SA", "nome": "Arabia Saudita", "nome_inglese": "Saudi Arabia", "continente": "AS", "nazionalita": "Saudita", "valuta": "SAR", "prefisso_telefonico": "+966"},
    {"codice_iso": "SEN", "codice_iso2": "SN", "nome": "Senegal", "nome_inglese": "Senegal", "continente": "AF", "nazionalita": "Senegalese", "valuta": "XOF", "prefisso_telefonico": "+221"},
    {"codice_iso": "SRB", "codice_iso2": "RS", "nome": "Serbia", "nome_inglese": "Serbia", "continente": "EU", "nazionalita": "Serba", "valuta": "RSD", "prefisso_telefonico": "+381"},
    {"codice_iso": "SYC", "codice_iso2": "SC", "nome": "Seychelles", "nome_inglese": "Seychelles", "continente": "AF", "nazionalita": "Seychellese", "valuta": "SCR", "prefisso_telefonico": "+248"},
    {"codice_iso": "SLE", "codice_iso2": "SL", "nome": "Sierra Leone", "nome_inglese": "Sierra Leone", "continente": "AF", "nazionalita": "Sierraleonese", "valuta": "SLL", "prefisso_telefonico": "+232"},
    {"codice_iso": "SGP", "codice_iso2": "SG", "nome": "Singapore", "nome_inglese": "Singapore", "continente": "AS", "nazionalita": "Singapore", "valuta": "SGD", "prefisso_telefonico": "+65"},
    {"codice_iso": "SVK", "codice_iso2": "SK", "nome": "Slovacchia", "nome_inglese": "Slovakia", "continente": "EU", "nazionalita": "Slovacca", "valuta": "EUR", "prefisso_telefonico": "+421"},
    {"codice_iso": "SVN", "codice_iso2": "SI", "nome": "Slovenia", "nome_inglese": "Slovenia", "continente": "EU", "nazionalita": "Slovena", "valuta": "EUR", "prefisso_telefonico": "+386"},
    {"codice_iso": "SLB", "codice_iso2": "SB", "nome": "Isole Salomone", "nome_inglese": "Solomon Islands", "continente": "OC", "nazionalita": "Salomoniana", "valuta": "SBD", "prefisso_telefonico": "+677"},
    {"codice_iso": "SOM", "codice_iso2": "SO", "nome": "Somalia", "nome_inglese": "Somalia", "continente": "AF", "nazionalita": "Somalo", "valuta": "SOS", "prefisso_telefonico": "+252"},
    {"codice_iso": "ZAF", "codice_iso2": "ZA", "nome": "Sudafrica", "nome_inglese": "South Africa", "continente": "AF", "nazionalita": "Sudafricana", "valuta": "ZAR", "prefisso_telefonico": "+27"},
    {"codice_iso": "SSD", "codice_iso2": "SS", "nome": "Sud Sudan", "nome_inglese": "South Sudan", "continente": "AF", "nazionalita": "Sud sudanese", "valuta": "SSP", "prefisso_telefonico": "+211"},
    {"codice_iso": "ESP", "codice_iso2": "ES", "nome": "Spagna", "nome_inglese": "Spain", "continente": "EU", "nazionalita": "Spagnola", "valuta": "EUR", "prefisso_telefonico": "+34"},
    {"codice_iso": "LKA", "codice_iso2": "LK", "nome": "Sri Lanka", "nome_inglese": "Sri Lanka", "continente": "AS", "nazionalita": "Singalese", "valuta": "LKR", "prefisso_telefonico": "+94"},
    {"codice_iso": "SDN", "codice_iso2": "SD", "nome": "Sudan", "nome_inglese": "Sudan", "continente": "AF", "nazionalita": "Sudanese", "valuta": "SDG", "prefisso_telefonico": "+249"},
    {"codice_iso": "SUR", "codice_iso2": "SR", "nome": "Suriname", "nome_inglese": "Suriname", "continente": "SA", "nazionalita": "Surinamese", "valuta": "SRD", "prefisso_telefonico": "+597"},
    {"codice_iso": "SWE", "codice_iso2": "SE", "nome": "Svezia", "nome_inglese": "Sweden", "continente": "EU", "nazionalita": "Svedese", "valuta": "SEK", "prefisso_telefonico": "+46"},
    {"codice_iso": "CHE", "codice_iso2": "CH", "nome": "Svizzera", "nome_inglese": "Switzerland", "continente": "EU", "nazionalita": "Svizzera", "valuta": "CHF", "prefisso_telefonico": "+41"},
    {"codice_iso": "SYR", "codice_iso2": "SY", "nome": "Siria", "nome_inglese": "Syria", "continente": "AS", "nazionalita": "Siriana", "valuta": "SYP", "prefisso_telefonico": "+963"},
    {"codice_iso": "TWN", "codice_iso2": "TW", "nome": "Taiwan", "nome_inglese": "Taiwan", "continente": "AS", "nazionalita": "Taiwanese", "valuta": "TWD", "prefisso_telefonico": "+886"},
    {"codice_iso": "TJK", "codice_iso2": "TJ", "nome": "Tagikistan", "nome_inglese": "Tajikistan", "continente": "AS", "nazionalita": "Tagika", "valuta": "TJS", "prefisso_telefonico": "+992"},
    {"codice_iso": "TZA", "codice_iso2": "TZ", "nome": "Tanzania", "nome_inglese": "Tanzania", "continente": "AF", "nazionalita": "Tanzaniana", "valuta": "TZS", "prefisso_telefonico": "+255"},
    {"codice_iso": "THA", "codice_iso2": "TH", "nome": "Thailandia", "nome_inglese": "Thailand", "continente": "AS", "nazionalita": "Thailandese", "valuta": "THB", "prefisso_telefonico": "+66"},
    {"codice_iso": "TLS", "codice_iso2": "TL", "nome": "Timor Est", "nome_inglese": "Timor-Leste", "continente": "AS", "nazionalita": "Timorense", "valuta": "USD", "prefisso_telefonico": "+670"},
    {"codice_iso": "TGO", "codice_iso2": "TG", "nome": "Togo", "nome_inglese": "Togo", "continente": "AF", "nazionalita": "Togolese", "valuta": "XOF", "prefisso_telefonico": "+228"},
    {"codice_iso": "TON", "codice_iso2": "TO", "nome": "Tonga", "nome_inglese": "Tonga", "continente": "OC", "nazionalita": "Tongana", "valuta": "TOP", "prefisso_telefonico": "+676"},
    {"codice_iso": "TTO", "codice_iso2": "TT", "nome": "Trinidad e Tobago", "nome_inglese": "Trinidad and Tobago", "continente": "NA", "nazionalita": "Trinidadiana", "valuta": "TTD", "prefisso_telefonico": "+1-868"},
    {"codice_iso": "TUN", "codice_iso2": "TN", "nome": "Tunisia", "nome_inglese": "Tunisia", "continente": "AF", "nazionalita": "Tunisina", "valuta": "TND", "prefisso_telefonico": "+216"},
    {"codice_iso": "TUR", "codice_iso2": "TR", "nome": "Turchia", "nome_inglese": "Turkey", "continente": "EU", "nazionalita": "Turca", "valuta": "TRY", "prefisso_telefonico": "+90"},
    {"codice_iso": "TKM", "codice_iso2": "TM", "nome": "Turkmenistan", "nome_inglese": "Turkmenistan", "continente": "AS", "nazionalita": "Turkmena", "valuta": "TMT", "prefisso_telefonico": "+993"},
    {"codice_iso": "TUV", "codice_iso2": "TV", "nome": "Tuvalu", "nome_inglese": "Tuvalu", "continente": "OC", "nazionalita": "Tuvaluana", "valuta": "AUD", "prefisso_telefonico": "+688"},
    {"codice_iso": "UGA", "codice_iso2": "UG", "nome": "Uganda", "nome_inglese": "Uganda", "continente": "AF", "nazionalita": "Ugandese", "valuta": "UGX", "prefisso_telefonico": "+256"},
    {"codice_iso": "UKR", "codice_iso2": "UA", "nome": "Ucraina", "nome_inglese": "Ukraine", "continente": "EU", "nazionalita": "Ucraina", "valuta": "UAH", "prefisso_telefonico": "+380"},
    {"codice_iso": "ARE", "codice_iso2": "AE", "nome": "Emirati Arabi Uniti", "nome_inglese": "United Arab Emirates", "continente": "AS", "nazionalita": "Emiratina", "valuta": "AED", "prefisso_telefonico": "+971"},
    {"codice_iso": "GBR", "codice_iso2": "GB", "nome": "Regno Unito", "nome_inglese": "United Kingdom", "continente": "EU", "nazionalita": "Britannica", "valuta": "GBP", "prefisso_telefonico": "+44"},
    {"codice_iso": "USA", "codice_iso2": "US", "nome": "Stati Uniti", "nome_inglese": "United States", "continente": "NA", "nazionalita": "Statunitense", "valuta": "USD", "prefisso_telefonico": "+1"},
    {"codice_iso": "URY", "codice_iso2": "UY", "nome": "Uruguay", "nome_inglese": "Uruguay", "continente": "SA", "nazionalita": "Uruguayana", "valuta": "UYU", "prefisso_telefonico": "+598"},
    {"codice_iso": "UZB", "codice_iso2": "UZ", "nome": "Uzbekistan", "nome_inglese": "Uzbekistan", "continente": "AS", "nazionalita": "Uzbeka", "valuta": "UZS", "prefisso_telefonico": "+998"},
    {"codice_iso": "VUT", "codice_iso2": "VU", "nome": "Vanuatu", "nome_inglese": "Vanuatu", "continente": "OC", "nazionalita": "Vanuatuana", "valuta": "VUV", "prefisso_telefonico": "+678"},
    {"codice_iso": "VAT", "codice_iso2": "VA", "nome": "Citt\u00e0 del Vaticano", "nome_inglese": "Vatican City", "continente": "EU", "nazionalita": "Vaticana", "valuta": "EUR", "prefisso_telefonico": "+379"},
    {"codice_iso": "VEN", "codice_iso2": "VE", "nome": "Venezuela", "nome_inglese": "Venezuela", "continente": "SA", "nazionalita": "Venezuelana", "valuta": "VES", "prefisso_telefonico": "+58"},
    {"codice_iso": "VNM", "codice_iso2": "VN", "nome": "Vietnam", "nome_inglese": "Vietnam", "continente": "AS", "nazionalita": "Vietnamita", "valuta": "VND", "prefisso_telefonico": "+84"},
    {"codice_iso": "YEM", "codice_iso2": "YE", "nome": "Yemen", "nome_inglese": "Yemen", "continente": "AS", "nazionalita": "Yemenita", "valuta": "YER", "prefisso_telefonico": "+967"},
    {"codice_iso": "ZMB", "codice_iso2": "ZM", "nome": "Zambia", "nome_inglese": "Zambia", "continente": "AF", "nazionalita": "Zambiana", "valuta": "ZMW", "prefisso_telefonico": "+260"},
    {"codice_iso": "ZWE", "codice_iso2": "ZW", "nome": "Zimbabwe", "nome_inglese": "Zimbabwe", "continente": "AF", "nazionalita": "Zimbabwese", "valuta": "ZWL", "prefisso_telefonico": "+263"},
]


def seed_nazioni():
    app = create_app()
    with app.app_context():
        db.create_all()
        count = 0
        for n in NAZIONI:
            if not Nazione.query.get(n["codice_iso"]):
                db.session.add(Nazione(**n))
                count += 1
        db.session.commit()
        print(f"✅ Inserite {count} nazioni (totale: {Nazione.query.count()})")


if __name__ == '__main__':
    seed_nazioni()
