"""Add BI models for charts and dashboards

Revision ID: 1c2c1d79bf1b
Revises: d459f024d470
Create Date: 2026-01-19 15:34:59.133808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2c1d79bf1b'
down_revision = 'd459f024d470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('layout', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('x_axis', sa.String(length=100), nullable=False),
    sa.Column('y_axis', sa.String(length=100), nullable=False),
    sa.Column('aggregation', sa.String(length=50), nullable=True),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['sys_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sys_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validation_regex', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('validation_message', sa.String(length=255), nullable=True))

    with op.batch_alter_table('sys_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_models', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    with op.batch_alter_table('sys_fields', schema=None) as batch_op:
        batch_op.drop_column('validation_message')
        batch_op.drop_column('validation_regex')

    op.drop_table('sys_charts')
    op.drop_table('sys_dashboards')
    # ### end Alembic commands ###
