"""Aggiunge relazione membri-progetti

Revision ID: 273d4507ec04
Revises: 87f92fd54913
Create Date: 2026-01-26 13:23:16.293082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273d4507ec04'
down_revision = '87f92fd54913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_members')
    # ### end Alembic commands ###
