"""Unified Module model with type, is_core, package support

Revision ID: 62be51d68d92
Revises: 8ab8c2608261
Create Date: 2026-02-28 08:46:04.734583

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "62be51d68d92"
down_revision = "8ab8c2608261"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("modules", schema=None) as batch_op:
        batch_op.add_column(sa.Column("type", sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column("is_core", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("category", sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column("is_free", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column("plan_required", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(sa.Column("version", sa.String(length=20), nullable=True))
        batch_op.add_column(
            sa.Column("core_version_min", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(), nullable=True))
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.drop_index(batch_op.f("ix_modules_project_status"))
        batch_op.drop_constraint(batch_op.f("uq_modules_name"), type_="unique")
        batch_op.drop_index(batch_op.f("ix_modules_name"))
        batch_op.create_index(batch_op.f("ix_modules_name"), ["name"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_modules_deleted_at"), ["deleted_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_modules_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_modules_type"), ["type"], unique=False)
        batch_op.create_index(
            "ix_modules_type_status", ["type", "status"], unique=False
        )
        batch_op.drop_constraint(
            batch_op.f("modules_project_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_column("project_id")

    # Note: module_projects and module_packages tables already exist from previous migration
    # No need to create them again

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("modules", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.create_foreign_key(
            batch_op.f("modules_project_id_fkey"), "projects", ["project_id"], ["id"]
        )
        batch_op.drop_index("ix_modules_type_status")
        batch_op.drop_index(batch_op.f("ix_modules_type"))
        batch_op.drop_index(batch_op.f("ix_modules_status"))
        batch_op.drop_index(batch_op.f("ix_modules_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_modules_name"))
        batch_op.create_index(batch_op.f("ix_modules_name"), ["name"], unique=False)
        batch_op.create_unique_constraint(
            batch_op.f("uq_modules_name"), ["name"], postgresql_nulls_not_distinct=False
        )
        batch_op.create_index(
            batch_op.f("ix_modules_project_status"),
            ["project_id", "status"],
            unique=False,
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("core_version_min")
        batch_op.drop_column("version")
        batch_op.drop_column("plan_required")
        batch_op.drop_column("price")
        batch_op.drop_column("is_free")
        batch_op.drop_column("category")
        batch_op.drop_column("is_core")
        batch_op.drop_column("type")

    # ### end Alembic commands ###
