"""Add project-scoped uniqueness for sysmodel names

Revision ID: 87f92fd54913
Revises: d8583977de68
Create Date: 2026-01-26 12:54:36.793707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87f92fd54913'
down_revision = 'd8583977de68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_kpi')
    with op.batch_alter_table('sys_models', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sys_models_name_key'), type_='unique')
        batch_op.create_unique_constraint('_project_model_name_uc', ['project_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_models', schema=None) as batch_op:
        batch_op.drop_constraint('_project_model_name_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('sys_models_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    op.create_table('dashboard_kpi',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('trend', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('dashboard_kpi_pkey'))
    )
    # ### end Alembic commands ###
