"""Add status to SysModel and create Module table

Revision ID: 8ab8c2608261
Revises: add_archetype_block_system
Create Date: 2026-02-28 08:02:18.446369

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ab8c2608261"
down_revision = "add_archetype_block_system"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_locations",
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uix_tenant_location_code"),
    )
    with op.batch_alter_table("inventory_locations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_locations_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "inventory_counts",
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("count_number", sa.String(length=50), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("scheduled_date", sa.Date(), nullable=True),
        sa.Column("completed_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["inventory_locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inventory_counts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_counts_count_number"),
            ["count_number"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_counts_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "product_stock",
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("reserved_quantity", sa.Float(), nullable=True),
        sa.Column("reorder_level", sa.Float(), nullable=True),
        sa.Column("reorder_quantity", sa.Float(), nullable=True),
        sa.Column("last_counted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["inventory_locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "product_id", "location_id", name="uix_tenant_product_location"
        ),
    )
    with op.batch_alter_table("product_stock", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_stock_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "stock_movements",
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("movement_number", sa.String(length=50), nullable=False),
        sa.Column("movement_type", sa.String(length=20), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("reference_type", sa.String(length=50), nullable=True),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["inventory_locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stock_movements", schema=None) as batch_op:
        batch_op.create_index(
            "ix_stock_movement_tenant_date", ["tenant_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stock_movements_movement_number"),
            ["movement_number"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stock_movements_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "inventory_count_lines",
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("count_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("expected_quantity", sa.Float(), nullable=True),
        sa.Column("counted_quantity", sa.Float(), nullable=True),
        sa.Column("variance", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["count_id"],
            ["inventory_counts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inventory_count_lines", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_count_lines_tenant_id"),
            ["tenant_id"],
            unique=False,
        )

    with op.batch_alter_table("sys_models", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(length=20), nullable=False))

    # Create modules table
    op.create_table(
        "modules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("api_definition", sa.JSON(), nullable=True),
        sa.Column("dependencies", sa.JSON(), nullable=True),
        sa.Column("test_suite_id", sa.Integer(), nullable=True),
        sa.Column("test_results", sa.JSON(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("menu_position", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_suite_id"],
            ["test_suites.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_modules_name"),
    )
    op.create_index("ix_modules_name", "modules", ["name"], unique=False)
    op.create_index(
        "ix_modules_project_status", "modules", ["project_id", "status"], unique=False
    )

    # Create module_models association table
    op.create_table(
        "module_models",
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("sysmodel_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sysmodel_id"],
            ["sys_models.id"],
        ),
        sa.PrimaryKeyConstraint("module_id", "sysmodel_id"),
    )

    # Create module_blocks association table
    op.create_table(
        "module_blocks",
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("block_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["blocks.id"],
        ),
        sa.PrimaryKeyConstraint("module_id", "block_id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sys_models", schema=None) as batch_op:
        batch_op.drop_column("status")

    with op.batch_alter_table("inventory_count_lines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_count_lines_tenant_id"))

    op.drop_table("inventory_count_lines")
    with op.batch_alter_table("stock_movements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stock_movements_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_stock_movements_movement_number"))
        batch_op.drop_index("ix_stock_movement_tenant_date")

    op.drop_table("stock_movements")
    with op.batch_alter_table("product_stock", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_stock_tenant_id"))

    op.drop_table("product_stock")
    with op.batch_alter_table("inventory_counts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_counts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_counts_count_number"))

    op.drop_table("inventory_counts")
    with op.batch_alter_table("inventory_locations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_locations_tenant_id"))

    op.drop_table("inventory_locations")
    # ### end Alembic commands ###
