"""Add summary_expression to SysField

Revision ID: 9885d7f529c1
Revises: f249ed895167
Create Date: 2026-01-19 14:11:04.243667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9885d7f529c1'
down_revision = 'f249ed895167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_expression', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_fields', schema=None) as batch_op:
        batch_op.drop_column('summary_expression')

    # ### end Alembic commands ###
