"""Add is_unique to SysField

Revision ID: d459f024d470
Revises: 9885d7f529c1
Create Date: 2026-01-19 14:14:46.241124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd459f024d470'
down_revision = '9885d7f529c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_unique', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_fields', schema=None) as batch_op:
        batch_op.drop_column('is_unique')

    # ### end Alembic commands ###
