"""Add content field to SysChart and make fields nullable

Revision ID: d8583977de68
Revises: 1c2c1d79bf1b
Create Date: 2026-01-19 15:54:34.445447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8583977de68'
down_revision = '1c2c1d79bf1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_charts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.alter_column('model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('x_axis',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('y_axis',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_charts', schema=None) as batch_op:
        batch_op.alter_column('y_axis',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('x_axis',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('content')

    # ### end Alembic commands ###
