"""Add Party model

Revision ID: eb1dc2c6636f
Revises: 7c6a11d0f109
Create Date: 2026-01-11 15:07:11.767016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1dc2c6636f'
down_revision = '7c6a11d0f109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('vat_number', sa.String(length=20), nullable=True),
    sa.Column('fiscal_code', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parties_fiscal_code'), ['fiscal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_vat_number'), ['vat_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parties_vat_number'))
        batch_op.drop_index(batch_op.f('ix_parties_name'))
        batch_op.drop_index(batch_op.f('ix_parties_fiscal_code'))

    op.drop_table('parties')
    # ### end Alembic commands ###
