"""Add formula to SysField

Revision ID: f249ed895167
Revises: bb77ccd0b494
Create Date: 2026-01-19 14:02:43.435900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f249ed895167'
down_revision = 'bb77ccd0b494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_value', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('formula', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_fields', schema=None) as batch_op:
        batch_op.drop_column('formula')
        batch_op.drop_column('default_value')

    # ### end Alembic commands ###
